---
apiVersion: v1
kind: Namespace
metadata:
  name: sunny-namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sunny-service-account
  namespace: sunny-namespace
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: sunny-service-account
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - nodes
      - pods
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - "extensions"
    resources:
      - ingresses/status
    verbs:
      - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: sunny-service-account
  namespace: sunny-namespace
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: sunny-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sunny-service-account
subjects:
  - kind: ServiceAccount
    name: sunny-service-account
    namespace: sunny-namespace
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: sunny-service-account
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: sunny-service-account
  namespace: sunny-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sunny-service-account
subjects:
  - kind: ServiceAccount
    name: sunny-service-account
    namespace: sunny-namespace
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: sunny-service-account
